### ISSUE TITLE
Hurdle container encounters error executing run_hurdle.py

### ISSUE THREAD

**Issue by FarshadKoohifar** [SpectrumCollaborationChallenge/phase2-hurdle#13]
Hi,

When I configure the bots in scoring mode using:
`./configure_bots.py --bot-type=scoring --image-name=darpa-scoring-srn-base-v2-1-0.tar.gz
`and do:
`./run_hurdle.py --duration=360 --image-file=Solution.tar.gz`
I get the error:
```
Traceback (most recent call last):
  File "./run_hurdle.py", line 545, in <module>
    main()
  File "./run_hurdle.py", line 368, in main
    bot_containers = [lxd_client.containers.get(name) for name in bot_container_names]
  File "./run_hurdle.py", line 368, in <listcomp>
    bot_containers = [lxd_client.containers.get(name) for name in bot_container_names]
  File "/usr/local/lib/python3.5/dist-packages/pylxd/models/container.py", line 105, in get
    response = client.api.containers[name].get()
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 106, in get
    self._assert_response(response, stream=kwargs.get('stream', False))
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 71, in _assert_response
    raise exceptions.NotFound(response)
pylxd.exceptions.NotFound: not found
```
I think the script is not handling the bot names correctly when the bots are in scoring mode (which changes the names of the containers to competitor-hurdle-srn).
 
Would you please let me know if you can reproduce the results using the last version of containers? ( version 2-1-0)

Farshad

**Comment by craig-pomeroy** [comment]
Ah, this is a documentation bug. It doesn't look like the docs included the command line parameter to switch the hurdle execution to use the scoring bot. 

If you run
```bash
./run_hurdle.py --help
```

you'll see the current set of command line args, which are currently

```bash
./run_hurdle.py --help
usage: run_hurdle [-h] [--bot-mode {practice,scoring,dummy}]
                  [--duration DURATION]
                  [--sample-rate {200000.0,500000.0,1000000.0,2000000.0}]
                  [--image-file IMAGE_FILE] [--disable-competitor-containers]
                  [--clean-competitor-containers] [--packet-rate PACKET_RATE]
                  [--noise-amp NOISE_AMP]
                  [--chan-gain-linear CHAN_GAIN_LINEAR]
                  [--enable-debug-output]

optional arguments:
  -h, --help            show this help message and exit
  --bot-mode {practice,scoring,dummy}
                        Practice or Scoring mode (default: practice)
  --duration DURATION   How long to run hurdle, not including bootup, in
                        seconds (default: 300.0)
  --sample-rate {200000.0,500000.0,1000000.0,2000000.0}
                        Sample rate to run the hurdle (default: 1000000.0)
  --image-file IMAGE_FILE
                        Name of the container stored in
                        /share/nas/competitor/images/ to use for this run
                        (default: competitor-image.tar.gz)
  --disable-competitor-containers
                        When specified, the run script will not use the
                        competitor containers (default: False)
  --clean-competitor-containers
                        When specified, this flag will make the run script
                        remove the competitor containers at the end of a run
                        (default: False)
  --packet-rate PACKET_RATE
                        Packet rate for bots and competitors (default: 15.0)
  --noise-amp NOISE_AMP
                        Amplitude of gaussian background noise (default:
                        0.0001)
  --chan-gain-linear CHAN_GAIN_LINEAR
                        Channel gain as a linear scalar applied to each
                        channel (default: 0.1)
  --enable-debug-output
                        When specified, this flag will run the envsim with a
                        ZMQ push socket that outputs the samples sent to
                        competitor containers (default: False)
```


Can you retry your run_hurdle command, using  --bot-mode=scoring
and let me know if that resolves your issue?

**Comment by craig-pomeroy** [comment]
Closing as this is now included in the Hurdle documentation.
